version: "3"
services:
  backend:
    env_file:
        "./server/dev.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: twitterServerBackend
    restart: always             
    ports:
      - "3002:3002"  
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    container_name: twitterFrontEnd
    ports:
      - "3000:3000"
    links:
      - "backend"